// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Follow struct {
	FollowingUserID pgtype.Int4
	FollowedUserID  pgtype.Int4
	CreatedAt       pgtype.Timestamp
}

type Post struct {
	ID    int32
	Title pgtype.Text
	// Content of the post
	Body      pgtype.Text
	UserID    pgtype.Int4
	Status    pgtype.Text
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID        int32
	Username  pgtype.Text
	Role      pgtype.Text
	CreatedAt pgtype.Timestamp
}
